stages:
  - test
  - deploy

variables:
  GIT_STRATEGY: clone

before_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - docker login -u $NDIP_DOCKER_USER -p $NDIP_DOCKER_PASSWORD $NDIP_DOCKER_REPOSITORY
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup

after_script:
  - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
  - source rse-bash-modules.sh
  - func_rse_docker_cleanup
  - sudo chown -R gitlab-runner .

test:
  stage: test
  script:
    - docker build -f dockerfiles/Dockerfile -t tutorial .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
  tags:
    - rse-multi-builder

pages:
  stage: deploy
  script:
  - docker build -t tutorial -f dockerfiles/Dockerfile .
  - mkdir public
  - docker run -v `pwd`/public:/app/site tutorial bash
  - cp $CALVERA_DOCS_SSH_KEY key && chmod 600 key
  - cat key
  - rsync -avz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i key" public/ cloud@10.64.195.250:/home/cloud/nova-tutorial/tutorial
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
      when: manual
    - when: on_success

  tags:
    - rse-multi-builder
